export const Pick5_Rules = `# PICK 5

## OFFICIAL RULES

**NO PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR WIN THIS SWEEPSTAKES. MAKING A PURCHASE OR PAYMENT OF ANY KIND WILL NOT INCREASE YOUR CHANCE OF WINNING A PRIZE. VOID WHERE PROHIBITED.**

**OPEN ONLY TO LEGAL RESIDENTS OF THE FIFTY UNITED STATES AND D.C. WHO ARE AGE 18 OR OLDER AT THE TIME OF ENTRY. U.S. LAW GOVERNS THIS SWEEPSTAKES.**

**YOUR ENTRY IN THIS SWEEPSTAKES MEANS THESE OFFICIAL RULES FORM A BINDING LEGAL CONTRACT, SO READ THEM CAREFULLY BEFORE PARTICIPATING. WITHOUT LIMITATION, THIS CONTRACT PROVIDES FOR YOUR INDEMNIFICATION OF THE SPONSOR AND OTHER PARTIES, THE WAIVER OF THE RIGHTS TO PARTICIPATE IN A CLASS ACTION OR A JURY TRIAL, AND A REQUIREMENT THAT MOST DISPUTES WILL BE SETTLED BY MANDATORY BINDING ARBITRATION.**

### ELIGIBILITY

The Receipts to Riches "Pick 5" Sweepstakes (the "Sweepstakes") is open only to legal residents of the fifty (50) United States and the District of Columbia, who are at least eighteen (18) years old and the age of majority in their state of legal residence. Employees of Receipts To Riches Inc. ("Sponsor"), its parent companies, subsidiaries, affiliates, distributors and advertising, promotion and Internet agencies, and members of the immediate family or household of any such employee, are not eligible. Void where prohibited by law. The Sweepstakes is subject to all applicable federal, state, and local laws and regulations. Participation constitutes the entrant's full and unconditional agreement to these Official Rules and Sponsor's decisions, which are final and binding in all matters related to the Sweepstakes. Winning a prize is contingent upon selected entrant fulfilling all requirements set forth herein.

### SPONSOR

The Sponsor is Receipts To Riches Inc., with an address at 16 Beverly Road, Englewood Cliffs, NJ 07632.

### SWEEPSTAKES ENTRY PERIOD

Mail in requests may be submitted beginning on August 01, 2026. The first daily entry period for the Sweepstakes begins at 12:00 a.m. Eastern Time ("ET") on August 01, 2026 and ends at 11:59 p.m. ET on August 01, 2026 (the "First Daily Entry Period"). Subsequent Daily Entry Periods shall begin each calendar day at 12:00 a.m. ET and end at 11:59 p.m. ET on the same calendar day (each a distinct "Daily Entry Period") until the Sweepstakes is terminated by Sponsor. Sponsor is the official timekeeper for this Sweepstakes.

### HOW TO ENTER THE SWEEPSTAKES

**Create a Receipt to Riches Account:** In order to enter the Sweepstakes, you must register for a Receipts to Riches account. It is free to create an account. To create an account, (i) go to the Sweepstakes download the Receipts to Riches mobile app for free (the "App"); (ii) click the link to "Register," (iii) follow the prompts to provide the requested information, namely first name, last name, email address, birthdate, phone number, address, and secret question and answer; (iv) check the box to agree to these Official Rules and the Privacy Policy; and (v) click "Register" to create your account.

**Obtain a Receipt:** Once you have registered, you must have a receipt in order to enter a Daily Sweepstakes. Each entrant must have in his or her possession at the time of entry a cash register receipt, a receipt issued online or by e-mail by a retailer or vendor or any other receipt that Sponsor in its discretion determines as evidence a sale by a vendor, store or similar establishment, with a total purchase price, including taxes, expressed in a maximum of five digits (a "Receipt"). Each entrant must have a separate Receipt with respect to each entry. There is a limit of one (1) Midday Drawing (defined below) entry and one (1) Pick 5 Drawing (defined below) entry per Receipt. If you do not have a Receipt, you may request one by mail as described below. The purchase amount is for winner selection purposes only. Each entry will be assigned an ID number by the Sponsor, which the entrant must write on the back of the Receipt for later verification. Entrants that enter via the Receipts to Riches App will have the option to upload a photo of the Receipt for recordkeeping purposes. Do not discard the Receipt. Store the Receipt in a safe place. Unless the Receipt has been successfully uploaded via the App, the physical Receipt will be required for verification purposes in the event you are selected as a potential winner.

Entrants can use any Receipt that they have in their possession. Entrants are not required to have purchased the relevant goods or services in order to use that receipt. In the event that an entrant does not have a Receipt, entrants can request a Receipt from Sponsor, as detailed below.

**If you do not have a Receipt** and would like to obtain one from Sponsor, beginning on August 01, 2026 and continuing throughout the entire Sweepstakes, print your name, mailing address and telephone number, the date of the Daily Sweepstakes you would like to enter, the specific Drawing you would like to enter (Midday Drawing or Pick 5 Drawing) and the words "PRINT RECEIPT" on a 3"x5" card. The date of the Daily Sweepstakes you would like to enter must be at least 10 days after the postmarked date. If you do not select a Daily Sweepstakes or the Daily Sweepstakes selected is not at least 10 days after the postmarked date, you will receive a Receipt for entry in the next available Daily Sweepstakes. Place the 3"x5" card and a stamped self-addressed envelope in a mailing envelope (except Vermont residents are not required to affix return postage), with proper first-class postage affixed, addressed to: Receipts to Riches, 16 Beverly Road, NJ 07632. Mail the envelope containing the card and self-addressed envelope to the address specified above. If you requested a Receipt, Sponsor will send back to you a randomly-generated computer-generated Receipt that may be used to enter the Sweepstakes. There is a limit of one request per envelope.

**Submit Your Entry:** Entries must be completed and received by Sponsor by the conclusion of the applicable Daily Entry Period. To enter, during the applicable Daily Entry Period, (i) access and log into the App; (ii) input the digits comprising the total purchase price shown on the Receipt (including taxes) and the time of purchase (expressed as a number of minutes) of entry. The first digit of the purchase price may be a zero if the total purchase price shown on the Receipt is less than $10.00. (For example, a total purchase price of $148.95 would be expressed using the digits 1-4-8-9-5). To be eligible to participate in this "Pick 5" Sweepstakes, the total purchase price must only be five digits; (iii) select if you would like to enter the Midday Drawing or the Pick 5 Drawing; and (iv) follow the prompts to submit your entry. If your Receipt does not show a time of purchase, you may follow the Quick Pick prompts to be randomly assigned a time of purchase.

**General Entry Conditions:** Each entrant must retain all Receipts used to enter the Sweepstakes for winner verification purposes. Entrants who enter the Sweepstakes via the Receipts to Riches App will have the option to take a photo of the applicable Receipt and save it to their account. When you participate in the Sweepstakes via mobile device, normal time rates, if any, charged by the entrant's Internet service provider may apply. The Sweepstakes is void where prohibited. There is a limit of one entry per Receipt.

All entries become the sole and exclusive property of Sponsor and will not be acknowledged or returned. Entries beyond the permitted number are void. Use of multiple email addresses, or any automated system to enter is prohibited and will result in disqualification.

### WINNER SELECTION

Two (2) daily Prizes (defined below) will be available each Daily Sweepstakes. On the day following each Daily Entry Period, at or about 8 p.m. ET, Sponsor will conduct two (2) drawings – a "Midday Drawing" and a "Pick 5 Drawing" (each a "Drawing") – where Sponsor randomly selects a five (5) digit purchase price and a four (4) digit time of day. Valid entries received during the applicable Daily Entry Period will be entered into the applicable selected Drawing for the Daily Sweepstakes. Entries do not rollover to subsequent Daily Sweepstakes on subsequent calendar days. If the purchase price and time of day submitted by an entrant each are identical to the purchase price and time of day generated at random by Sponsor (a "Winning Combination"), the entrant will be a potential winner of that Drawing, subject to verification. There may be more than one (1) Daily Winner for each Drawing in each Daily Sweepstakes, but there will not be a Daily Winner for any Daily Sweepstakes or Drawing where no entrant submits a Winning Combination. If multiple entrants submit a Winning Combination for a Drawing, the single Prize for that Drawing will be divided equally among the winning entrants. The odds of winning a Prize are approximately 142,560,000 to 1.

### PRIZES

Each available Prize is $5,000, to be provided via a payment method determined by Sponsor ("Prize"). There is one (1) Prize per Drawing. All federal, state, local taxes on the value of each Prize, if applicable, are the responsibility of the winner. An IRS form 1099-MISC will be issued in each winner's name if required by law. The Prizes will be awarded if properly claimed. No substitution, cash redemption or transfer of the right to receive any prize is permitted, except at the discretion of Sponsor, which reserves the right to substitute a Prize or Prize component of equal or greater value. All expenses or costs associated with the acceptance or use of any Prize that are not expressly specified in these Official Rules as being part of the Prize are the responsibility of the winner. Sponsor reserves the right in its discretion to provide any or all Prizes on a payment schedule over a time period and in installment amounts determined by Sponsor. Sponsor reserves the right in its discretion to award additional "bonus" prizes from time to time (but is not under any obligation to do so).

### WINNER NOTIFICATION AND VERIFICATION

Each potential winner will be notified by mail, telephone and/or e-mail, at Sponsor's discretion. If a potential winner cannot be reached within seventy-two (72) hours of the initial notification attempt, he or she may be disqualified. The winners are subject to verification. No entrant will be deemed a winner until verification has been completed. The potential winners may, in Sponsor's discretion, be required to complete and return to Sponsor an Affidavit of Eligibility/Release of Liability, and, if legally permissible, a Publicity Release within five (5) days of attempted delivery of same. Potential winners may also in Sponsor's discretion be required to provide the original Receipt and must cooperate with whatever other verification measures are deemed appropriate by Sponsor. If a potential winner fails to respond to any notification attempt within the time period specified by Sponsor, or if any attempted notification or prize delivery is returned as undeliverable, or if a potential winner fails to complete and return any required affidavit or release within the specified time period, the potential winner will be disqualified and an alternate winner selected. Sponsor reserves the right to modify the notification and affidavit procedures in connection with the selection of alternate potential prize winner, if any.

### ENTRY CONDITIONS AND RELEASE

By entering, each entrant agrees to: (a) comply with and be bound by these Official Rules and the decisions of the Sponsor and/or its designee(s) which are binding and final in all matters relating to these Sweepstakes; (b) release and hold harmless Sponsor and its respective parent, subsidiary and affiliated companies, the Prize suppliers and any other organizations and/or persons responsible for sponsoring, fulfilling, administering, advertising or promoting the Sweepstakes, and all of their respective past and present officers, directors, employees, agents and representatives (collectively, the "Released Parties") from and against any and all claims, expenses and liability, including but not limited to negligence and damages of any kind to persons and property, including but not limited to invasion of privacy (under appropriation, intrusion, public disclosure of private facts, false light in the public eye or other legal theory), defamation, slander, libel, violation of right of publicity, infringement of trademark, copyright or other intellectual property rights, property damage, or death or personal injury arising out of or relating to a participant's entry, creation of an entry or submission of an entry, participation in the Sweepstakes, acceptance or use or misuse of Prize (including any travel or activity related thereto) and/or the broadcast, exploitation or use of entry; and (c) indemnify, defend, and hold harmless the Released Parties from and against any and all claims, expenses, and liabilities (including reasonable attorneys' fees) arising out of or relating to an entrant's participation in the Sweepstakes and/or entrant's acceptance, use or misuse of any Prize.

The Released Parties are not responsible for: (a) any incorrect or inaccurate information, whether caused by entrant, or programming associated with or used in the Sweepstakes; (b) technical failures of any kind, including but not limited to malfunctions, interruptions, or disconnections in phone lines or network hardware or software; (c) unauthorized human intervention in any part of the entry process or the Sweepstakes; (d) technical or human error, which may occur in the administration of the Sweepstakes or the processing of entries; (e) any injury or damage to persons or property, which may be caused, directly or indirectly, in whole or in part, from entrant's participation in the Sweepstakes or receipt or use or misuse of any Prize; or (f) entries, prize claims or notifications that are lost, late, incomplete, illegible, unintelligible, damaged or otherwise not received by the intended recipient, in whole or in part, due to computer, human or technical error of any kind, including but not limited to, by reason of unauthorized human intervention, spam filters, privacy settings, inactive email accounts or an entrant's failure to monitor its email account. If for any reason an entrant's entry is confirmed to have been erroneously deleted, lost or otherwise destroyed or corrupted, entrant's sole remedy is another entry in the Sweepstakes. No more than the stated number of Prizes will be awarded. If, for any reason, the Sweepstakes cannot be executed as planned, including, but not limited to, any governmental order, epidemic, pandemic, force majeure, social media mandate, printing, administrative or other error of any kind, transmission failure, infection by computer virus, bugs, tampering, unauthorized intervention, fraud, technical failures, or any other causes beyond the control of Sponsor that corrupt or affect the security, administration, fairness, integrity or proper conduct of the Sweepstakes, or if the Sweepstakes is compromised or becomes technically corrupted in any way, electronically or otherwise, Sponsor reserves the right, in its sole discretion, to cancel, modify or terminate the Sweepstakes and, if a Daily Sweepstakes is terminated before the original end date, to include only all eligible, non-suspect entries received as of the date/time of termination as entrants in the applicable Drawing.

### PUBLICITY

Except where prohibited, entrants agree that participation in the Sweepstakes constitutes verified prize winners' consent to Sponsor's and its agents' use of each such winner's name, likeness, photograph, voice, opinions and/or hometown and state for promotional purposes in any media (whether now known or invented in the future), worldwide, without further limitation, restriction, notice, review, approval, payment or consideration but that Sponsor is not required to make such use.

### GENERAL CONDITIONS

Sponsor reserves the right to cancel, suspend and/or modify the Sweepstakes, or any part of it including any Daily Sweepstakes, if any fraud, technical failures or any other factor beyond Sponsor's reasonable control impairs the integrity or proper functioning of the Sweepstakes, as determined by Sponsor in its sole discretion. Sponsor reserves the right in its sole discretion to disqualify any individual it finds to be tampering with the entry process or the operation of the Sweepstakes or to be acting in violation of these Official Rules or any other promotion or in an unsportsmanlike or disruptive manner. Any attempt by any person to deliberately undermine the legitimate operation of the Sweepstakes may be a violation of criminal and civil law and, should such an attempt be made, Sponsor reserves the right to seek damages from any such person to the fullest extent permitted by law. Sponsor's failure to enforce any term of these Official Rules shall not constitute a waiver of that provision.

In the event of a dispute regarding the identity of any entrant, the authorized account holder of the email address used to enter the Sweepstakes will be deemed to be the entrant. The "authorized account holder" is the natural person assigned an email address by an Internet access provider, online service provider or other organization responsible for assigning email addresses for the domain associated with the submitted address. Potential prize winner(s) of any Prize may be required to show proof of being the authorized account holder to be awarded the Prize. All entry information becomes the sole and exclusive property of Sponsor and will not be returned or cancelled.

### LIMITATIONS OF LIABILITY

**BY ENTERING THE SWEEPSTAKES, ENTRANT AGREES THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW: (1) ANY AND ALL DISPUTES, CLAIMS AND CAUSES OF ACTION ARISING OUT OF OR CONNECTED WITH THE SWEEPSTAKES, OR ANY PRIZE(S) AWARDED WILL BE LIMITED TO ACTUAL, OUT-OF-POCKET COSTS INCURRED (IF ANY) NOT TO EXCEED TEN DOLLARS ($10.00), BUT IN NO EVENT WILL ATTORNEYS' FEES BE AWARDED OR RECOVERABLE; AND (2) UNDER NO CIRCUMSTANCES WILL ANY ENTRANT BE PERMITTED TO OBTAIN ANY AWARD FOR, AND ENTRANT HEREBY KNOWINGLY AND EXPRESSLY WAIVES ALL RIGHTS TO SEEK, PUNITIVE, INCIDENTAL, CONSEQUENTIAL OR SPECIAL DAMAGES, LOST PROFITS AND/OR ANY OTHER DAMAGES AND/OR ANY RIGHTS TO HAVE DAMAGES MULTIPLIED OR OTHERWISE INCREASED.**

**SOME JURISDICTIONS DO NOT ALLOW THE FOREGOING LIMITATIONS OR EXCLUSION OF LIABILITY, SO THE ABOVE MAY NOT APPLY TO YOU.**

**FOR CALIFORNIA ENTRANTS:** EACH ENTRANT UNDERSTANDS AND AGREES THAT ALL RIGHTS UNDER SECTION 1542 OF THE CIVIL CODE OF CALIFORNIA AND ANY SIMILAR LAW OF ANY STATE OF THE UNITED STATES ARE HEREBY EXPRESSLY WAIVED BY HIM/HER AGAINST THE RELEASED PARTIES. SECTION 1542 READS AS FOLLOWS:

> "CERTAIN CLAIMS NOT AFFECTED BY A GENERAL RELEASE. A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS THAT THE CREDITOR OR RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE AND THAT, IF KNOWN BY HIM OR HER, WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR OR RELEASED PARTY."

### BINDING ARBITRATION AGREEMENT AND CLASS ACTION WAIVER

Except where prohibited by law, as a condition of participating in this Sweepstakes, each entrant agrees as follows:

**Binding Arbitration Agreement.** Except as otherwise stated below, any and all legal issue, claim or dispute arising out of or connected or related in any way to the Sweepstakes, including but not limited to prize awarded, shall be resolved through final, binding arbitration. Entrant specifically agrees that, except as otherwise provided herein, entry into the Sweepstakes waives all rights to bring a lawsuit based on such claim(s) or dispute(s) and the right to have such lawsuit resolved by a judge or a jury.

This Arbitration Agreement shall be governed by the Federal Arbitration Act, (9 U.S.C. § 1 et seq.). Any arbitration will be commenced and administered by JAMS under the rules of JAMS, including [JAMS Consumer Arbitration Minimum Standards](https://www.jamsadr.com/consumer-minimum-standards/). If JAMS' criteria are met by the nature of the dispute, the entrant agrees that the arbitration shall be conducted under [JAMS Streamlined Arbitration Rules & Procedures](https://www.jamsadr.com/rules-streamlined-arbitration/). Judgment upon any arbitration award may be entered in any court of appropriate jurisdiction.

Each party will pay the fees for his/her or its own attorneys, subject to any remedies to which that party may later be entitled under applicable law. However, if entrant is unable to pay JAMS' costs, Sponsor will pay all arbitration fees and expenses. If JAMS is unavailable, unwilling, or otherwise unable to administer an arbitration in accordance with these rules, then another arbitration administrator will do, to be selected by agreement of the parties.

Neither entrant nor Sponsor shall be permitted to obtain awards, and all parties hereby waive all rights to claim, punitive, incidental, or consequential damages, or any other damages, including attorneys' fees, other than entrant's actual out-of-pocket expenses (i.e., costs associated with participating in this Sweepstakes). The parties further waive all rights to have damages multiplied or increased.

The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon both you and us. Additionally, the arbitrator, and not any federal, state, or local court or agency, shall have the exclusive authority to resolve any dispute relating to the interpretation, applicability, enforceability, or formation of this Arbitration Agreement, except that this sentence shall not apply to the Class Action Waiver provisions described below. The arbitrator will render a decision in writing. A court of competent jurisdiction shall have the authority to enter judgment upon the arbitrator's decision/award. This Arbitration Agreement will survive the termination of your relationship with us.

**Excluded Disputes.** Notwithstanding the binding arbitration requirement set forth in this section, entrant may bring qualifying claims in small claims court so long as the matter remains in such court and advances only on an individual, non-class, non-representative basis.

**Class Action Waiver.** To fullest extent permitted by applicable law, you and we agree to bring any claim or dispute, whether in arbitration, or court as permitted by these terms, ON AN INDIVIDUAL BASIS ONLY, AND NOT AS A CLASS ACTION OR COLLECTIVE ACTION. There shall be no right or authority for any claim or dispute to be brought, heard or arbitrated as a class or collective action ("Class Action Waiver"). The arbitration will decide the rights and liabilities, if any, of you and us. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator may award any remedy to which a party is entitled under applicable law, but remedies shall be limited to those that would be available to a party in their individual capacity. Regardless of anything else in this Arbitration Agreement and/or the applicable JAMS rules, the interpretation, applicability, enforceability or formation of the Class Action Waiver may only be determined by a court and not an arbitrator. This Class-Action Waiver will survive the termination of your relationship with us.

**One-Year Time Limit to Raise Disputes or Claims.** You agree that any dispute, claim or lawsuit, regardless of form, that may arise out of or related to the Sweepstakes, must be filed within ONE (1) YEAR of the action, omission, event or occurrence giving rise to the dispute, claim(s) or lawsuit. After the expiration of the one-year period, such dispute, claim(s) or lawsuit will be time-barred and prohibited, without regard to any longer period of time which may be provided by any period of limitation or pursuant to law or statute.

**Waiver of Jury Trial.** BOTH ENTRANT AND SPONSOR HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, except as provided herein. We are instead mutually electing that all disputes, claims, or requests for relief shall be resolved by arbitration under this Arbitration Agreement, except as specified herein. An arbitrator can award on an individual basis the same damages and relief as a court and must follow this Agreement as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.

**Location of Arbitration.** Entrant may choose to have the arbitration conducted by video conference technology such as zoom or based on written submissions. Otherwise, the location of the arbitration proceeding shall take place in the city or state where entrant resides, unless each party to the arbitration agrees otherwise, or at another mutually agreed upon location.

### GOVERNING LAW

These Official Rules and any disputes between us shall be governed by the laws of the State of New Jersey without giving effect to any choice of law or conflict of law rules (whether of the State of New Jersey or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than the State of New Jersey.

### SEVERABILITY

In the event any provision of these Official Rules is determined to be void or unenforceable, such determination shall not affect the remainder of these terms, which shall continue to be in force.

### ENTRANT'S PERSONAL INFORMATION

When registering for the Sweepstakes, you expressly agree to receive promotional communications from Sponsor. Information collected from entrants is subject to the Sponsor's Privacy Policy, which is available at Receipts To Riches App. If you are selected as a potential or verified prize winner, your name, city and state may also be included in a publicly available Winners' List.

### WINNER'S NAME AND RULES REQUESTS

Winners will be announced on the App as they are verified. In addition, to receive the names of the winners by mail, or a copy of these Official Rules, send a self-addressed, stamped envelope to: Receipts To Riches Pick 5 Sweepstakes, 16 Beverly Road, Englewood Cliffs, NJ 07632. You must identify the applicable Daily Sweepstakes and Drawing in your request.

### Questions?

Please email support@receiptstoriches.com

---

*Note: Neither Apple or Google are involved in any way with the contest or sweepstakes.*
`;

export const Pick5_Rules_es = `# SELECCIÓN 5 (PICK 5)

## REGLAS OFICIALES

**NO ES NECESARIA NINGUNA COMPRA O PAGO DE NINGÚN TIPO PARA PARTICIPAR O GANAR EN ESTE SORTEO. HACER UNA COMPRA O PAGO DE NINGÚN TIPO NO AUMENTARÁ SUS POSIBILIDADES DE GANAR UN PREMIO. NULO DONDE ESTÉ PROHIBIDO.**

**ABIERTO SÓLO PARA RESIDENTES LEGALES DE LOS CINCUENTA ESTADOS UNIDOS Y D.C. QUE TENGAN 18 AÑOS DE EDAD O MÁS AL MOMENTO DE LA PARTICIPACIÓN. LAS LEYES DE LOS EE. UU. RIGEN ESTE SORTEO.**

**SU PARTICIPACIÓN EN ESTE SORTEO SIGNIFICA QUE ESTAS REGLAS OFICIALES CONSTITUYEN UN CONTRATO LEGAL VINCULANTE, ASÍ QUE LÉALAS DETENIDAMENTE ANTES DE PARTICIPAR. SIN LIMITACIÓN, ESTE CONTRATO PREVÉ SU INDEMNIZACIÓN AL PATROCINADOR Y A OTRAS PARTES, LA RENUNCIA A LOS DERECHOS DE PARTICIPAR EN UNA ACCIÓN COLECTIVA O UN JUICIO POR JURADO, Y EL REQUISITO DE QUE LA MAYORÍA DE LAS DISPUTAS SE RESOLVERÁN MEDIANTE ARBITRAJE VINCULANTE OBLIGATORIO.**

### ELEGIBILIDAD

El Sorteo "Pick 5" de Receipts to Riches (el "Sorteo") está abierto sólo a residentes legales de los cincuenta (50) Estados Unidos y el Distrito de Columbia, que tengan al menos dieciocho (18) años de edad y la mayoría de edad en su estado de residencia legal. Los empleados de Receipts To Riches Inc. ("Patrocinador"), sus empresas matrices, subsidiarias, afiliadas, distribuidores y agencias de publicidad, promoción e Internet, y los miembros de la familia inmediata o del hogar de cualquier empleado de este tipo, no son elegibles. Nulo donde esté prohibido por la ley. El Sorteo está sujeto a todas las leyes y regulaciones federales, estatales y locales aplicables. La participación constituye el acuerdo total e incondicional del participante con estas Reglas Oficiales y las decisiones del Patrocinador, las cuales son finales y vinculantes en todos los asuntos relacionados con el Sorteo. Ganar un premio está condicionado al cumplimiento de todos los requisitos aquí establecidos por parte del participante seleccionado.

### PATROCINADOR

El Patrocinador es Receipts To Riches Inc., con dirección en 16 Beverly Road, Englewood Cliffs, NJ 07632.

### PERÍODO DE PARTICIPACIÓN DEL SORTEO

Las solicitudes por correo se pueden enviar a partir del 1 de agosto de 2026. El primer período de participación diario para el Sorteo comienza a las 12:00 a.m. hora del este ("ET") el 1 de agosto de 2026 y finaliza a las 11:59 p.m. ET el 1 de agosto de 2026 (el "Primer Período de Entrada Diario"). Los períodos de entrada diarios subsiguientes comenzarán cada día calendario a las 12:00 a.m. ET y finalizarán a las 11:59 p.m. ET del mismo día calendario (cada uno un "Período de Entrada Diario" distinto) hasta que el Sorteo sea cancelado por el Patrocinador. El Patrocinador es el cronometrador oficial de este Sorteo.

### CÓMO PARTICIPAR EN EL SORTEO

**Crear una Cuenta de Receipts to Riches:** Para participar en el Sorteo, debe registrarse para obtener una cuenta de Receipts to Riches. Crear una cuenta es gratis. Para crear una cuenta, (i) vaya a la descarga del Sorteo y descargue la aplicación móvil Receipts to Riches de forma gratuita (la "Aplicación"); (ii) haga clic en el enlace para "Registrarse"; (iii) siga las instrucciones para proporcionar la información solicitada, es decir, nombre, apellido, dirección de correo electrónico, fecha de nacimiento, número de teléfono, dirección y pregunta y respuesta secretas; (iv) marque la casilla para aceptar estas Reglas Oficiales y la Política de Privacidad; y (v) haga clic en "Registrarse" para crear su cuenta.

**Obtener un Recibo:** Una vez registrado, debe tener un recibo para participar en un Sorteo Diario. Cada participante debe tener en su posesión al momento de participar un recibo de caja registradora, un recibo emitido en línea o por correo electrónico por un minorista o proveedor, o cualquier otro recibo que el Patrocinador determine a su discreción como evidencia de una venta por parte de un proveedor, tienda o establecimiento similar, con un precio de compra total, incluidos los impuestos, expresado en un máximo de cinco dígitos (un "Recibo"). Cada participante debe tener un Recibo separado para cada participación. Existe un límite de una (1) participación para el Sorteo del Mediodía (definido a continuación) y una (1) participación para el Sorteo de Pick 5 (definido a continuación) por Recibo. Si no tiene un Recibo, puede solicitar uno por correo como se describe a continuación. El monto de la compra es solo para fines de selección de ganadores. A cada participación se le asignará un número de identificación por parte del Patrocinador, que el participante debe escribir en el reverso del Recibo para su posterior verificación. Los participantes que ingresen a través de la aplicación Receipts to Riches tendrán la opción de subir una foto del Recibo para fines de mantenimiento de registros. No deseche el Recibo. Guarde el Recibo en un lugar seguro. A menos que el Recibo haya sido subido con éxito a través de la aplicación, se requerirá el Recibo físico para fines de verificación en caso de que sea seleccionado como un ganador potencial.

Los participantes pueden usar cualquier Recibo que tengan en su poder. Los participantes no están obligados a haber comprado los bienes o servicios correspondientes para poder utilizar ese recibo. En caso de que un participante no tenga un Recibo, los participantes pueden solicitar un Recibo al Patrocinador, como se detalla a continuación.

**Si no tiene un Recibo** y desea obtener uno del Patrocinador, a partir del 1 de agosto de 2026 y durante todo el Sorteo, imprima su nombre, dirección postal y número de teléfono, la fecha del Sorteo Diario en el que desea participar, el Sorteo específico en el que desea participar (Sorteo del Mediodía o Sorteo de Pick 5) y las palabras "PRINT RECEIPT" (IMPRIMIR RECIBO) en una tarjeta de 3"x5". La fecha del Sorteo Diario en el que desea participar debe ser al menos 10 días posterior a la fecha del matasellos. Si no selecciona un Sorteo Diario o si el Sorteo Diario seleccionado no es al menos 10 días posterior a la fecha del matasellos, recibirá un Recibo para participar en el próximo Sorteo Diario disponible. Coloque la tarjeta de 3"x5" y un sobre con estampilla y su dirección en un sobre de envío (excepto los residentes de Vermont que no están obligados a adjuntar franqueo de devolución), con el franqueo de primera clase adecuado, dirigido a: Receipts to Riches, 16 Beverly Road, NJ 07632. Envíe por correo el sobre que contiene la tarjeta y el sobre con su dirección a la dirección especificada anteriormente. Si solicitó un Recibo, el Patrocinador le devolverá un Recibo generado aleatoriamente por computadora que podrá utilizar para participar en el Sorteo. Hay un límite de una solicitud por sobre.

**Envíe su Participación:** Las participaciones deben completarse y ser recibidas por el Patrocinador antes de la conclusión del Período de Entrada Diario aplicable. Para participar, durante el Período de Entrada Diario aplicable, (i) acceda e inicie sesión en la Aplicación; (ii) ingrese los dígitos que componen el precio de compra total que se muestra en el Recibo (incluidos los impuestos) y la hora de compra (expresada como una cantidad de minutos) de la participación. El primer dígito del precio de compra puede ser un cero si el precio de compra total que se muestra en el Recibo es inferior a $10.00 (por ejemplo, un precio de compra total de $148.95 se expresaría utilizando los dígitos 1-4-8-9-5). Para ser elegible para participar en este Sorteo "Pick 5", el precio total de compra debe ser de solo cinco dígitos; (iii) seleccione si desea participar en el Sorteo del Mediodía o en el Sorteo de Pick 5; y (iv) siga las instrucciones para enviar su participación. Si su Recibo no muestra una hora de compra, puede seguir las instrucciones de Selección Rápida para que se le asigne una hora de compra al azar.

**Condiciones Generales de Participación:** Cada participante debe conservar todos los Recibos utilizados para participar en el Sorteo para fines de verificación del ganador. Los participantes que ingresen al Sorteo a través de la aplicación Receipts to Riches tendrán la opción de tomar una foto del Recibo aplicable y guardarla en su cuenta. Cuando participe en el Sorteo a través de un dispositivo móvil, se aplicarán las tarifas normales de tiempo, si las hubiera, cobradas por el proveedor de servicios de Internet del participante. El Sorteo es nulo donde esté prohibido. Hay un límite de una participación por Recibo.

Todas las participaciones pasan a ser propiedad única y exclusiva del Patrocinador y no serán reconocidas ni devueltas. Las participaciones que superen el número permitido son nulas. Está prohibido el uso de múltiples direcciones de correo electrónico o cualquier sistema automatizado para participar y resultará en la descalificación.

### SELECCIÓN DE GANADORES

Dos (2) Premios diarios (definidos a continuación) estarán disponibles en cada Sorteo Diario. Al día siguiente a cada Período de Entrada Diario, a las 8 p.m. ET o aproximadamente a esa hora, el Patrocinador llevará a cabo dos (2) sorteos: un "Sorteo del Mediodía" y un "Sorteo de Pick 5" (cada uno un "Sorteo"), donde el Patrocinador seleccionará al azar un precio de compra de cinco (5) dígitos y una hora del día de cuatro (4) dígitos. Las participaciones válidas recibidas durante el Período de Entrada Diario aplicable se ingresarán en el Sorteo seleccionado aplicable para el Sorteo Diario. Las participaciones no se acumulan para los Sorteos Diarios subsiguientes en los días calendario siguientes. Si el precio de compra y la hora del día presentados por el participante son idénticos al precio de compra y la hora del día generados al azar por el Patrocinador (una "Combinación Ganadora"), el participante será un ganador potencial de ese Sorteo, sujeto a verificación. Puede haber más de un (1) Ganador Diario para cada Sorteo en cada Sorteo Diario, pero no habrá un Ganador Diario para ningún Sorteo Diario o Sorteo en el que ningún participante presente una Combinación Ganadora. Si varios participantes presentan una Combinación Ganadora para un Sorteo, el Premio único para ese Sorteo se dividirá por igual entre los participantes ganadores. Las probabilidades de ganar un Premio son aproximadamente de 142,560,000 a 1.

### PREMIOS

Cada Premio disponible es de $5,000, que se entregará a través de un método de pago determinado por el Patrocinador ("Premio"). Hay un (1) Premio por Sorteo. Todos los impuestos federales, estatales y locales sobre el valor de cada Premio, si corresponden, son responsabilidad del ganador. Se emitirá un formulario IRS 1099-MISC a nombre de cada ganador si lo exige la ley. Los Premios se otorgarán si se reclaman correctamente. No se permite la sustitución, el canje en efectivo o la transferencia del derecho a recibir cualquier premio, excepto a discreción del Patrocinador, que se reserva el derecho de sustituir un Premio o componente del Premio por otro de igual o mayor valor. Todos los gastos o costos asociados con la aceptación o el uso de cualquier Premio que no estén expresamente especificados en estas Reglas Oficiales como parte del Premio son responsabilidad del ganador. El Patrocinador se reserva el derecho, a su discreción, de proporcionar cualquiera o todos los Premios en un cronograma de pago durante un período de tiempo y en montos de cuotas determinados por el Patrocinador. El Patrocinador se reserva el derecho, a su discreción, de otorgar premios "adicionales" de vez en cuando (pero no está bajo ninguna obligación de hacerlo).

### NOTIFICACIÓN Y VERIFICACIÓN DE GANADORES

Cada ganador potencial será notificado por correo postal, teléfono y/o correo electrónico, a discreción del Patrocinador. Si no se puede contactar a un ganador potencial dentro de las setenta y dos (72) horas posteriores al intento de notificación inicial, puede ser descalificado. Los ganadores están sujetos a verificación. Ningún participante será considerado ganador hasta que se haya completado la verificación. Los ganadores potenciales pueden, a discreción del Patrocinador, estar obligados a completar y devolver al Patrocinador una Declaración Jurada de Elegibilidad/Exención de Responsabilidad y, si es legalmente permisible, una Autorización de Publicidad dentro de los cinco (5) días posteriores al intento de entrega de la misma. Los ganadores potenciales también pueden, a discreción del Patrocinador, estar obligados a proporcionar el Recibo original y deben cooperar con cualquier otra medida de verificación que el Patrocinador considere adecuada. Si un ganador potencial no responde a cualquier intento de notificación dentro del período de tiempo especificado por el Patrocinador, o si cualquier intento de notificación o entrega del premio se devuelve como no entregable, o si un ganador potencial no completa y devuelve cualquier declaración jurada o autorización requerida dentro del período de tiempo especificado, el ganador potencial será descalificado y se seleccionará un ganador alternativo. El Patrocinador se reserva el derecho de modificar los procedimientos de notificación y declaración jurada en relación con la selección de un ganador potencial de premio alternativo, si lo hubiera.

### CONDICIONES DE PARTICIPACIÓN Y EXENCIÓN DE RESPONSABILIDAD

Al participar, cada participante acepta: (a) cumplir y estar sujeto a estas Reglas Oficiales y las decisiones del Patrocinador y/o sus designados, que son vinculantes y definitivas en todos los asuntos relacionados con este Sorteo; (b) liberar y eximir de responsabilidad al Patrocinador y a sus respectivas empresas matrices, subsidiarias y afiliadas, a los proveedores de los Premios y a cualquier otra organización y/o persona responsable del patrocinio, cumplimiento, administración, publicidad o promoción del Sorteo, y a todos sus respectivos funcionarios, directores, empleados, agentes y representantes pasados y presentes (colectivamente, las "Partes Liberadas") de y contra cualquier reclamación, gasto y responsabilidad, incluyendo pero no limitado a negligencia y daños de cualquier tipo a personas y propiedad, incluyendo pero no limitado a invasión de privacidad (bajo apropiación, intrusión, divulgación pública de hechos privados, falsa luz a los ojos del público u otra teoría legal), difamación, calumnia, libelo, violación del derecho de publicidad, infracción de marca registrada, derechos de autor u otros derechos de propiedad intelectual, daños a la propiedad, o muerte o lesiones personales que surjan de o estén relacionadas con la participación de un participante, la creación de una participación o el envío de una participación, la participación en el Sorteo, la aceptación o el uso o mal uso del Premio (incluyendo cualquier viaje o actividad relacionada con el mismo) y/o la difusión, explotación o uso de la participación; y (c) indemnizar, defender y eximir de responsabilidad a las Partes Liberadas de y contra cualquier reclamación, gasto y responsabilidad (incluidos los honorarios razonables de abogados) que surjan de o estén relacionados con la participación de un participante en el Sorteo y/o la aceptación, uso o mal uso de cualquier Premio por parte del participante.

Las Partes Liberadas no son responsables de: (a) cualquier información incorrecta o inexacta, ya sea causada por el participante o por la programación asociada con el Sorteo o utilizada en él; (b) fallas técnicas de cualquier tipo, incluyendo pero no limitado a mal funcionamiento, interrupciones o desconexiones en líneas telefónicas o hardware o software de red; (c) intervención humana no autorizada en cualquier parte del proceso de participación o del Sorteo; (d) error técnico o humano, que pueda ocurrir en la administración del Sorteo o en el procesamiento de las participaciones; (e) cualquier lesión o daño a personas o propiedad, que pueda ser causado, directa o indirectamente, en todo o en parte, por la participación del participante en el Sorteo o la recepción, uso o mal uso de cualquier Premio; o (f) participaciones, reclamaciones de premios o notificaciones que se pierdan, retrasen, estén incompletas, sean ilegibles, ininteligibles, estén dañadas o que de otro modo no sean recibidas por el destinatario previsto, en todo o en parte, debido a un error informático, humano o técnico de cualquier tipo, incluyendo pero no limitado a, por motivos de intervención humana no autorizada, filtros de correo no deseado (spam), configuraciones de privacidad, cuentas de correo electrónico inactivas o la falla del participante en monitorear su cuenta de correo electrónico. Si por alguna razón se confirma que la participación de un participante fue borrada, perdida o destruida o dañada por error, el único remedio del participante es otra participación en el Sorteo. No se otorgarán más premios de los establecidos. Si por alguna razón el Sorteo no puede llevarse a cabo según lo planeado, incluyendo pero no limitado a cualquier orden gubernamental, epidemia, pandemia, fuerza mayor, mandato de redes sociales, error de impresión, administrativo o de otro tipo de cualquier tipo, falla de transmisión, infección por virus informático, errores, alteración, intervención no autorizada, fraude, fallas técnicas o cualquier otra causa fuera del control del Patrocinador que corrompa o afecte la seguridad, administración, equidad, integridad o conducta adecuada del Sorteo, o si el Sorteo se ve comprometido o se corrompe técnicamente de alguna manera, electrónicamente o de otro modo, el Patrocinador se reserva el derecho, a su entera discreción, de cancelar, modificar o dar por terminado el Sorteo y, si un Sorteo Diario se da por terminado antes de la fecha de finalización original, de incluir únicamente todas las participaciones elegibles y no sospechosas recibidas hasta la fecha/hora de la terminación como participantes en el Sorteo aplicable.

### PUBLICIDAD

Excepto donde esté prohibido, los participantes aceptan que la participación en el Sorteo constituye el consentimiento de los ganadores de premios verificados para que el Patrocinador y sus agentes utilicen el nombre, imagen, fotografía, voz, opiniones y/o ciudad natal y estado de cada uno de dichos ganadores para fines promocionales en cualquier medio (ya sea conocido ahora o inventado en el futuro), en todo el mundo, sin más limitaciones, restricciones, avisos, revisiones, aprobaciones, pagos o contraprestaciones, pero el Patrocinador no está obligado a hacer dicho uso.

### CONDICIONES GENERALES

El Patrocinador se reserva el derecho de cancelar, suspender y/o modificar el Sorteo, o cualquier parte del mismo, incluyendo cualquier Sorteo Diario, si algún fraude, fallas técnicas o cualquier otro factor fuera del control razonable del Patrocinador afecta la integridad o el funcionamiento adecuado del Sorteo, según lo determine el Patrocinador a su entera discreción. El Patrocinador se reserva el derecho, a su entera discreción, de descalificar a cualquier persona que considere que está alterando el proceso de participación o el funcionamiento del Sorteo o que está actuando en violación de estas Reglas Oficiales o de cualquier otra promoción o de una manera antideportiva o perturbadora. Cualquier intento por parte de cualquier persona de socavar deliberadamente el funcionamiento legítimo del Sorteo puede ser una violación de las leyes penales y civiles y, en caso de que se realice tal intento, el Patrocinador se reserva el derecho de reclamar daños y perjuicios a dicha persona en la medida máxima permitida por la ley. La falla del Patrocinador en hacer cumplir cualquier término de estas Reglas Oficiales no constituirá una renuncia a dicha disposición.

En caso de disputa sobre la identidad de cualquier participante, se considerará que el titular autorizado de la cuenta de correo electrónico utilizada para participar en el Sorteo es el participante. El "titular autorizado de la cuenta" es la persona física asignada a una dirección de correo electrónico por un proveedor de acceso a Internet, proveedor de servicios en línea u otra organización responsable de asignar direcciones de correo electrónico para el dominio asociado con la dirección presentada. Los ganadores potenciales de cualquier Premio pueden ser requeridos a mostrar prueba de ser el titular autorizado de la cuenta para recibir el Premio. Toda la información de participación se convierte en propiedad única y exclusiva del Patrocinador y no será devuelta ni cancelada.

### LIMITACIONES DE RESPONSABILIDAD

**AL PARTICIPAR EN EL SORTEO, EL PARTICIPANTE ACEPTA QUE, EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY APLICABLE: (1) TODAS Y CADA UNA DE LAS DISPUTAS, RECLAMACIONES Y CAUSAS DE ACCIÓN QUE SURJAN DE O ESTÉN CONECTADAS CON EL SORTEO, O CUALQUIER PREMIO OTORGADO, SE LIMITARÁN A LOS COSTOS REALES DE BOLSILLO INCURRIDOS (SI LOS HUBIERA) QUE NO EXCEDAN LOS DIEZ DÓLARES ($10.00), PERO EN NINGÚN CASO SE OTORGARÁN O RECUPERARÁN HONORARIOS DE ABOGADOS; Y (2) BAJO NINGUNA CIRCUNSTANCIA SE PERMITIRÁ A NINGÚN PARTICIPANTE OBTENER NINGUNA COMPENSACIÓN POR, Y EL PARTICIPANTE POR LA PRESENTE RENUNCIA A TODOS LOS DERECHOS A RECLAMAR, DAÑOS PUNITIVOS, INCIDENTALES, CONSECUENTES O ESPECIALES, PÉRDIDA DE GANANCIAS Y/O CUALQUIER OTRO DAÑO Y/O CUALQUIER DERECHO A QUE LOS DAÑOS SE MULTIPLIQUEN O SE INCREMENTEN DE OTRO MODO.**

**ALGUNAS JURISDICCIONES NO PERMITEN LAS LIMITACIONES O EXCLUSIONES DE RESPONSABILIDAD ANTERIORES, POR LO QUE LO ANTERIOR PUEDE NO APLICARSE EN SU CASO.**

**PARA PARTICIPANTES DE CALIFORNIA:** CADA PARTICIPANTE ENTIENDE Y ACEPTA QUE TODOS LOS DERECHOS BAJO LA SECCIÓN 1542 DEL CÓDIGO CIVIL DE CALIFORNIA Y CUALQUIER LEY SIMILAR DE CUALQUIER ESTADO DE LOS ESTADOS UNIDOS SON EXPRESAMENTE RENUNCIADOS POR ÉL/ELLA CONTRA LAS PARTES LIBERADAS. LA SECCIÓN 1542 SE LEE DE LA SIGUIENTE MANERA:

> "UNA EXENCIÓN GENERAL NO SE EXTIENDE A LAS RECLAMACIONES QUE EL ACREEDOR O LA PARTE LIBERADORA NO CONOZCA O SOSPECHE QUE EXISTEN A SU FAVOR AL MOMENTO DE EJECUTAR LA EXENCIÓN Y QUE, DE HABER SIDO CONOCIDAS POR ÉL O ELLA, HABRÍAN AFECTADO MATERIALMENTE SU ACUERDO CON EL DEUDOR O LA PARTE LIBERADA."

### ACUERDO DE ARBITRAJE VINCULANTE Y RENUNCIA A ACCIONES COLECTIVAS

Excepto donde lo prohíba la ley, como condición para participar en este Sorteo, cada participante acepta lo siguiente:

**Acuerdo de Arbitraje Vinculante.** Excepto que se indique lo contrario a continuación, cualquier asunto legal, reclamación o disputa que surja de o esté conectada o relacionada de alguna manera con el Sorteo, incluyendo pero no limitado al premio otorgado, se resolverá mediante arbitraje final y vinculante. El participante acepta específicamente que, excepto que se disponga lo contrario en este documento, la participación en el Sorteo renuncia a todos los derechos de presentar una demanda basada en dicha reclamación o disputa y al derecho de que dicha demanda sea resuelta por un juez o un jurado.

Este Acuerdo de Arbitraje se regirá por la Ley Federal de Arbitraje (9 U.S.C. § 1 y siguientes). Cualquier arbitraje se iniciará y administrará por JAMS según las reglas de JAMS, incluyendo los Estándares Mínimos de Arbitraje del Consumidor de JAMS https://www.jamsadr.com/consumer-minimum-standards/. Si se cumplen los criterios de JAMS por la naturaleza de la disputa, el participante acepta que el arbitraje se llevará a cabo bajo las Reglas y Procedimientos Simplificados de Arbitraje de JAMS https://www.jamsadr.com/rules-streamlined-arbitration/. La sentencia sobre cualquier laudo arbitral puede presentarse en cualquier tribunal de jurisdicción apropiada.

Cada parte pagará los honorarios de sus propios abogados, sujeto a cualquier recurso al que esa parte pueda tener derecho más adelante según la ley aplicable. Sin embargo, si el participante no puede pagar los costos de JAMS, el Patrocinador pagará todos los honorarios y gastos de arbitraje. Si JAMS no está disponible, no está dispuesto o no puede administrar un arbitraje de acuerdo con estas reglas, se seleccionará otro administrador de arbitraje por acuerdo de las partes.

Ni el participante ni el Patrocinador podrán obtener indemnizaciones por daños y perjuicios, y todas las partes renuncian por la presente a todos los derechos a reclamar daños punitivos, incidentales o consecuentes, o cualquier otro daño, incluidos los honorarios de abogados, que no sean los gastos reales de bolsillo del participante (es decir, los costos asociados con la participación en este Sorteo). Las partes renuncian además a todo derecho a que los daños se multipliquen o aumenten. El árbitro tiene la misma autoridad para otorgar una compensación de forma individual que la que tendría un juez en un tribunal de justicia. El laudo del árbitro es final y vinculante para usted y para nosotros. Además, el árbitro, y no ningún tribunal o agencia federal, estatal o local, tendrá la autoridad exclusiva para resolver cualquier disputa relacionada con la interpretación, aplicabilidad, exigibilidad o formación de este Acuerdo de Arbitraje, excepto que esta frase no se aplicará a las disposiciones de Renuncia a Acciones Colectivas descritas a continuación. El árbitro emitirá una decisión por escrito. Un tribunal de jurisdicción competente tendrá la autoridad para registrar la sentencia sobre la decisión/laudo del árbitro. Este Acuerdo de Arbitraje sobrevivirá a la terminación de su relación con nosotros.

**Disputas Excluidas.** Sin perjuicio del requisito de arbitraje vinculante establecido en esta sección, el participante puede presentar reclamaciones que califiquen en un tribunal de demandas menores, siempre que el asunto permanezca en dicho tribunal y avance solo de manera individual, no colectiva y no representativa.

**Renuncia a Acciones Colectivas.** En la medida máxima permitida por la ley aplicable, usted y nosotros aceptamos presentar cualquier reclamación o disputa, ya sea en arbitraje o en los tribunales según lo permitido por estos términos, ÚNICAMENTE DE MANERA INDIVIDUAL, Y NO COMO UNA ACCIÓN COLECTIVA O COLECTIVA. No habrá derecho ni autoridad para que cualquier reclamación o disputa sea presentada, escuchada o arbitrada como una acción colectiva o colectiva ("Renuncia a Acciones Colectivas"). El arbitraje decidirá los derechos y responsabilidades, si los hubiera, de usted y de nosotros. El procedimiento de arbitraje no se consolidará con ningún otro asunto ni se unirá con ningún otro caso o parte. El árbitro puede otorgar cualquier remedio al que una parte tenga derecho según la ley aplicable, pero los remedios se limitarán a aquellos que estarían disponibles para una parte en su capacidad individual. Independientemente de cualquier otra disposición de este Acuerdo de Arbitraje y/o de las reglas de JAMS aplicables, la interpretación, aplicabilidad, exigibilidad o formación de la Renuncia a Acciones Colectivas solo puede ser determinada por un tribunal y no por un árbitro. Esta Renuncia a Acciones Colectivas sobrevivirá a la terminación de su relación con nosotros.

**Límite de un Año para Plantear Disputas o Reclamaciones:** Usted acepta que cualquier disputa, reclamación o demanda, independientemente de su forma, que pueda surgir de o estar relacionada con el Sorteo, debe presentarse dentro de UN (1) AÑO de la acción, omisión, evento u ocurrencia que dé lugar a la disputa, reclamación o demanda. Después del vencimiento del período de un año, dicha disputa, reclamación o demanda prescribirá y estará prohibida, sin tener en cuenta ningún período de limitación más largo que pueda estar previsto por cualquier ley o estatuto.

**Renuncia a Juicio por Jurado.** TANTO EL PARTICIPANTE COMO EL PATROCINADOR RENUNCIAN POR LA PRESENTE A CUALQUIER DERECHO CONSTITUCIONAL Y LEGAL A DEMANDAR EN UN TRIBUNAL Y A TENER UN JUICIO ANTE UN JUEZ O UN JURADO, excepto como se proporciona en este documento. En su lugar, elegimos mutuamente que todas las disputas, reclamaciones o solicitudes de alivio se resuelvan mediante arbitraje bajo este Acuerdo de Arbitraje, excepto como se especifica en este documento. Un árbitro puede otorgar de forma individual los mismos daños y el mismo alivio que un tribunal y debe cumplir con este Acuerdo de la misma manera que lo haría un tribunal. Sin embargo, no hay juez ni jurado en el arbitraje, y la revisión judicial de un laudo arbitral está sujeta a una revisión muy limitada.

**Ubicación del Arbitraje.** El participante puede elegir que el arbitraje se realice mediante tecnología de videoconferencia como Zoom o sobre la base de presentaciones escritas. De lo contrario, la ubicación del procedimiento de arbitraje se llevará a cabo en la ciudad o estado donde resida el participante, a menos que cada parte del arbitraje acuerde lo contrario, o en otra ubicación mutuamente acordada.

### LEY APLICABLE

Estas Reglas Oficiales y cualquier disputa entre nosotros se regirán por las leyes del Estado de Nueva Jersey sin dar efecto a ninguna elección de ley o reglas de conflicto de leyes (ya sea del Estado de Nueva Jersey o de cualquier otra jurisdicción), que causarían la aplicación de las leyes de cualquier jurisdicción que no sea el Estado de Nueva Jersey.

### DIVISIBILIDAD

En caso de que cualquier disposición de estas Reglas Oficiales se determine que es nula o inaplicable, dicha determinación no afectará al resto de estos términos, que continuarán vigentes.

### INFORMACIÓN PERSONAL DEL PARTICIPANTE

Al registrarse en el Sorteo, usted acepta expresamente recibir comunicaciones promocionales del Patrocinador. La información recopilada de los participantes está sujeta a la Política de Privacidad del Patrocinador, que está disponible en la Aplicación Receipts To Riches. Si es seleccionado como un ganador potencial o verificado del premio, su nombre, ciudad y estado también pueden ser incluidos en una Lista de Ganadores disponible públicamente.

### NOMBRE DEL GANADOR Y SOLICITUD DE REGLAS

Los ganadores serán anunciados en la Aplicación a medida que sean verificados. Además, para recibir los nombres de los ganadores por correo o una copia de estas Reglas Oficiales, envíe un sobre con estampilla y su dirección a: Receipts To Riches Pick 5 Sweepstakes, 16 Beverly Road, Englewood Cliffs, NJ 07632. Debe identificar las fechas aplicables del Sorteo Diario y del Sorteo en su solicitud.

### ¿Preguntas?

Envíe un correo electrónico a support@receiptstoriches.com

---

*Nota: Ni Apple ni Google están involucrados de ninguna manera con el concurso o sorteo.*
`;
