export const dropdownConfig: Record<
  string,
  Array<{ label: string; value: string | number }>
> = {
  paymentMethods: [
    { label: 'dropdowns.paymentMethods.cash', value: 'cash' },
    { label: 'dropdowns.paymentMethods.debit_card', value: 'debit_card' },
    { label: 'dropdowns.paymentMethods.credit_card', value: 'credit_card' },
    { label: 'dropdowns.paymentMethods.mobile_wallet', value: 'mobile_wallet' },
    { label: 'dropdowns.paymentMethods.bank_transfer', value: 'bank_transfer' },
  ],
  receiptStatus: [
    { label: 'dropdowns.receiptStatus.pending', value: 'pending' },
    { label: 'dropdowns.receiptStatus.approved', value: 'approved' },
    { label: 'dropdowns.receiptStatus.rejected', value: 'rejected' },
  ],
  titleOptions: [
    { label: 'dropdowns.titles.mr', value: 'Mr' },
    { label: 'dropdowns.titles.mrs', value: 'Mrs' },
    { label: 'dropdowns.titles.ms', value: 'Ms' },
    { label: 'dropdowns.titles.dr', value: 'Dr' },
  ],
  cityOptions: [
    { label: 'dropdowns.cities.new_york', value: 'new_york' },
    { label: 'dropdowns.cities.los_angeles', value: 'los_angeles' },
    { label: 'dropdowns.cities.chicago', value: 'chicago' },
    { label: 'dropdowns.cities.houston', value: 'houston' },
  ],
  stateOptions: [
    { label: 'dropdowns.states.AL', value: 'AL' },
    { label: 'dropdowns.states.AK', value: 'AK' },
    { label: 'dropdowns.states.AZ', value: 'AZ' },
    { label: 'dropdowns.states.AR', value: 'AR' },
    { label: 'dropdowns.states.CA', value: 'CA' },
    { label: 'dropdowns.states.CO', value: 'CO' },
    { label: 'dropdowns.states.CT', value: 'CT' },
    { label: 'dropdowns.states.DE', value: 'DE' },
    { label: 'dropdowns.states.FL', value: 'FL' },
    { label: 'dropdowns.states.GA', value: 'GA' },
    { label: 'dropdowns.states.HI', value: 'HI' },
    { label: 'dropdowns.states.ID', value: 'ID' },
    { label: 'dropdowns.states.IL', value: 'IL' },
    { label: 'dropdowns.states.IN', value: 'IN' },
    { label: 'dropdowns.states.IA', value: 'IA' },
    { label: 'dropdowns.states.KS', value: 'KS' },
    { label: 'dropdowns.states.KY', value: 'KY' },
    { label: 'dropdowns.states.LA', value: 'LA' },
    { label: 'dropdowns.states.ME', value: 'ME' },
    { label: 'dropdowns.states.MD', value: 'MD' },
    { label: 'dropdowns.states.MA', value: 'MA' },
    { label: 'dropdowns.states.MI', value: 'MI' },
    { label: 'dropdowns.states.MN', value: 'MN' },
    { label: 'dropdowns.states.MS', value: 'MS' },
    { label: 'dropdowns.states.MO', value: 'MO' },
    { label: 'dropdowns.states.MT', value: 'MT' },
    { label: 'dropdowns.states.NE', value: 'NE' },
    { label: 'dropdowns.states.NV', value: 'NV' },
    { label: 'dropdowns.states.NH', value: 'NH' },
    { label: 'dropdowns.states.NJ', value: 'NJ' },
    { label: 'dropdowns.states.NM', value: 'NM' },
    { label: 'dropdowns.states.NY', value: 'NY' },
    { label: 'dropdowns.states.NC', value: 'NC' },
    { label: 'dropdowns.states.ND', value: 'ND' },
    { label: 'dropdowns.states.OH', value: 'OH' },
    { label: 'dropdowns.states.OK', value: 'OK' },
    { label: 'dropdowns.states.OR', value: 'OR' },
    { label: 'dropdowns.states.PA', value: 'PA' },
    { label: 'dropdowns.states.RI', value: 'RI' },
    { label: 'dropdowns.states.SC', value: 'SC' },
    { label: 'dropdowns.states.SD', value: 'SD' },
    { label: 'dropdowns.states.TN', value: 'TN' },
    { label: 'dropdowns.states.TX', value: 'TX' },
    { label: 'dropdowns.states.UT', value: 'UT' },
    { label: 'dropdowns.states.VT', value: 'VT' },
    { label: 'dropdowns.states.VA', value: 'VA' },
    { label: 'dropdowns.states.WA', value: 'WA' },
    { label: 'dropdowns.states.WV', value: 'WV' },
    { label: 'dropdowns.states.WI', value: 'WI' },
    { label: 'dropdowns.states.WY', value: 'WY' },
  ],
  secretQuestionOptions: [
    { label: 'dropdowns.secretQuestions.first_pet', value: 'first_pet' },
    { label: 'dropdowns.secretQuestions.mother_maiden', value: 'mother_maiden' },
    {
      label: 'dropdowns.secretQuestions.elementary_school',
      value: 'elementary_school',
    },
    { label: 'dropdowns.secretQuestions.birth_city', value: 'birth_city' },
    { label: 'dropdowns.secretQuestions.first_car', value: 'first_car' },
    { label: 'dropdowns.secretQuestions.favorite_food', value: 'favorite_food' },
    { label: 'dropdowns.secretQuestions.nickname', value: 'nickname' },
    {
      label: 'dropdowns.secretQuestions.favorite_teacher',
      value: 'favorite_teacher',
    },
  ],
};
