export interface ThemeColors {
  primary: string;
  minicard: string;
  secondary: string;
  inputbackground: string;
  inputbackground2: string;
  inputBorder: string;
  borderColor1: string;
  divColor: string;
  infocard: string;
  searchColor: string;
  card: string;
  info: string;
  white: string;
  text: string;
  text_color: string;
  secondaryText: string;
  secondary_text_color: string;
  transparent: string;
  inActiveColor: string;
  background: string;
  black: string;
  lightGray: string;
  border: string;
  borderColor: string;
  brown: string;
  green: string;
  success: string;
  warning: string;
  lightGreen: string;
  gray: string;
  gray2: string;
  darkGray: string;
  error: string;
  bottomStack: string;
  bottomIcon: string;
  btnText: string;
  screenBg: string;
  screenBg2: string;
  header: string;
  Golden: string;
}

export const LightColors: ThemeColors = {
  primary: '#D5AD60',
  Golden: '#FFD700',
  minicard: '#151A2A',
  screenBg: '#F5F5F5',
  screenBg2: '#ffffffff',
  secondary: '#274C66',
  inputbackground: '#F5F5F5',
  inputbackground2: '#FFFFFF',
  inputBorder: '#212C59',
  borderColor1: '#02050F',
  divColor: '#061032',
  infocard: '#0E121F',
  searchColor: '#202951',
  card: '#FFFFFF',
  header: '#ffff',
  info: '#151B2E',
  white: '#FFFFFF',
  text: '#000000ff',
  btnText: '#FFFFFF',
  text_color: '#274C66',
  secondaryText: '#565656',
  secondary_text_color: '#565656',
  transparent: 'transparent',
  inActiveColor: '#C0C0C0',
  background: '#F5F5F5',
  black: '#000000',
  lightGray: '#F5F5F5',
  border: '#EBEBEB',
  borderColor: '#EBEBEB',
  brown: '#8B4513',
  green: '#00674D',
  success: '#00674D',
  warning: '#F59E0B',
  lightGreen: '#5bc6abff',
  gray: '#757575',
  gray2: '#DCDCDC',
  darkGray: '#757575',
  error: '#ff2e47ff',
  bottomStack: '#FFFFFF',
  bottomIcon: '#DCDCDC',
};

export default LightColors;
