const NavigationStrings = {
  AUTH_STACK: 'AUTH_STACK',
  USER_STACK: 'USER_STACK',
  BOTTOM_STACK: 'BOTTOM_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  APP_STACK: 'APP_STACK',
  PLAY_STACK: 'PLAY_STACK',
  SOCIAL_STACK: 'SOCIAL_STACK',

  //Auth Screens
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  OTP: 'OTP',
  NEW_PASSWORD: 'NEW_PASSWORD',

  //USER STACK SCREENS
  BASIC_INFO: 'BASIC_INFO',
  SECRET_QUESTION: 'SECRET_QUESTION',
  GUIDE_VIDEO: 'GUIDE_VIDEO',

  //AppStack Screens
  HOME: 'HOME',
  FEED: 'FEED',
  SCAN: 'SCAN',
  REWARDS: 'REWARDS',
  RANKINGS: 'RANKINGS',
  NOTIFICATION: 'NOTIFICATION',
  VIDEO_AD: 'VIDEO_AD',
  SOCIAL_PROFILE: 'SOCIAL_PROFILE',
  SOCIAL_CONNECTIONS: 'SOCIAL_CONNECTIONS',
  USER_POSTS: 'USER_POSTS',
  CREATE_POST: 'CREATE_POST',

  //Profile Stack Screens
  PROFILE: 'PROFILE',
  PERSONAL_INFO: 'PERSONAL_INFO',
  PASSWORD_SCREEN: 'PASSWORD_SCREEN',
  MY_RECEIPTS: 'MY_RECEIPTS',
  TERMS_N_CONDITION: 'TERMS_N_CONDITION',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  HELP_N_SUPPORT: 'HELP_N_SUPPORT',
  ABOUT_US: 'ABOUT_US',
  RULES: 'RULES',
  EXPLAINER_VIDEO: 'EXPLAINER_VIDEO',
  LANGUAGES: 'Languages',
  MANAGE_CAMPAIGNS: 'MANAGE_CAMPAIGNS',
  CAMPAIGN_DETAIL: 'CAMPAIGN_DETAIL',
  CAMPAIGN_WEBVIEW: 'CAMPAIGN_WEBVIEW',
  CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',

  //PlayStack Screens
  PLAY: 'PLAY',
  PICPICK: 'PICPICK',
  PICPICK_GAME: 'PICPICK_GAME',
  CASH_GAME: 'CASH_GAME',
  SPIN_WHEEL: 'SPIN_WHEEL',
  SCRATCH_2_WIN: 'SCRATCH_2_WIN',
  LUCKY_7: 'LUCKY_7',
  WINNERS: 'WINNERS',
} as const;

export default NavigationStrings;
